using System.Collections.Generic;
using System.Globalization;
using System.Text;
using UnityEngine;

namespace emiteat.NexUI.Designer.Editor.Serialization
{
    /// <summary>
    /// Generates UXML + USS text from Designer metadata (brief §31/§39.2). Deliberately a pure
    /// string generator with no file I/O and no VisualTreeAsset dependency, so it is fully
    /// unit-testable and — crucially — so codegen NEVER rewrites a hand-authored UXML in place.
    /// The write path (see the generation window) always targets a SEPARATE generated file, which is
    /// the safe merge strategy called for by the Architecture Audit (migration risk 2): the source
    /// UXML authored in UI Builder is never touched.
    ///
    /// Layout maps the Designer's absolute-canvas-rect model onto <c>position: absolute</c> USS with
    /// per-element left/top from each element's parent-relative local position, so nested elements
    /// place correctly under their parent.
    /// </summary>
    public static class UIToolkitCodeGenerator
    {
        private const string GeneratedBanner = "<!-- NEXUI:GENERATED - regenerated by NexUI Designer. Do not hand-edit; edit in the Designer instead. -->";

        // ---- UXML ---------------------------------------------------------------

        public static string GenerateUxml(DesignerMetadataAsset metadata)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<ui:UXML xmlns:ui=\"UnityEngine.UIElements\" xmlns:uie=\"UnityEditor.UIElements\">");
            sb.Append("    ").AppendLine(GeneratedBanner);

            if (metadata != null)
                foreach (var root in DesignerHierarchyUtility.GetRootElements(metadata))
                    AppendUxmlElement(sb, metadata, root, 1);

            sb.AppendLine("</ui:UXML>");
            return sb.ToString();
        }

        private static void AppendUxmlElement(StringBuilder sb, DesignerMetadataAsset metadata, DesignerElementMetadata element, int depth)
        {
            if (element == null || string.IsNullOrEmpty(element.elementId)) return;

            var indent = new string(' ', depth * 4);
            var tag = TagFor(element.elementType);
            var children = DesignerHierarchyUtility.GetOrderedChildren(metadata, element.elementId);

            sb.Append(indent).Append('<').Append(tag);
            sb.Append(" name=\"").Append(EscapeAttr(element.elementId)).Append('"');

            var classAttr = ClassAttr(element);
            if (!string.IsNullOrEmpty(classAttr))
                sb.Append(" class=\"").Append(EscapeAttr(classAttr)).Append('"');

            if (HasText(element.elementType) && !string.IsNullOrEmpty(element.text))
                sb.Append(" text=\"").Append(EscapeAttr(element.text)).Append('"');

            if (children.Count == 0)
            {
                sb.AppendLine(" />");
                return;
            }

            sb.AppendLine(">");
            foreach (var child in children)
                AppendUxmlElement(sb, metadata, child, depth + 1);
            sb.Append(indent).Append("</").Append(tag).AppendLine(">");
        }

        // ---- USS ----------------------------------------------------------------

        public static string GenerateUss(DesignerMetadataAsset metadata)
        {
            var sb = new StringBuilder();
            sb.Append("/* ").Append("NEXUI:GENERATED - regenerated by NexUI Designer. Do not hand-edit.").AppendLine(" */");

            if (metadata != null)
                foreach (var element in metadata.elements)
                    AppendUssRule(sb, metadata, element);

            return sb.ToString();
        }

        private static void AppendUssRule(StringBuilder sb, DesignerMetadataAsset metadata, DesignerElementMetadata element)
        {
            if (element == null || string.IsNullOrEmpty(element.elementId)) return;

            var parent = string.IsNullOrEmpty(element.parentId) ? null : metadata.Find(element.parentId);
            var parentLayout = parent != null && parent.autoLayout != null && parent.autoLayout.enabled ? parent.autoLayout : null;

            sb.Append('#').Append(element.elementId).AppendLine(" {");

            if (parentLayout != null)
                AppendFlowChildLayout(sb, metadata, element, parentLayout);
            else
                AppendAbsoluteLayout(sb, metadata, element);

            if (HasText(element.elementType))
            {
                sb.Append("    color: ").Append(Rgba(element.textColor)).AppendLine(";");
                sb.Append("    font-size: ").Append(element.fontSize).AppendLine("px;");
            }
            else
            {
                sb.Append("    background-color: ").Append(Rgba(element.tint)).AppendLine(";");
            }

            // This element is itself an Auto Layout container: arrange its children with flex.
            if (element.autoLayout != null && element.autoLayout.enabled)
            {
                var al = element.autoLayout;
                sb.Append("    flex-direction: ")
                  .Append(al.direction == DesignerAutoLayoutDirection.Row ? "row" : "column").AppendLine(";");
                sb.Append("    padding: ")
                  .Append(Px(al.paddingTop)).Append(' ').Append(Px(al.paddingRight)).Append(' ')
                  .Append(Px(al.paddingBottom)).Append(' ').Append(Px(al.paddingLeft)).AppendLine(";");
            }

            if (element.hiddenInDesigner)
                sb.AppendLine("    display: none;");
            if (element.clipChildren)
                sb.AppendLine("    overflow: hidden;");

            sb.AppendLine("}");
        }

        /// <summary>Absolute positioning from the element's parent-relative local position (used when
        /// the parent is not an Auto Layout container).</summary>
        private static void AppendAbsoluteLayout(StringBuilder sb, DesignerMetadataAsset metadata, DesignerElementMetadata element)
        {
            var local = DesignerCoordinateUtility.GetLocalPosition(metadata, element);
            sb.AppendLine("    position: absolute;");
            sb.Append("    left: ").Append(Px(local.x)).AppendLine(";");
            sb.Append("    top: ").Append(Px(local.y)).AppendLine(";");
            sb.Append("    width: ").Append(Px(element.rect.width)).AppendLine(";");
            sb.Append("    height: ").Append(Px(element.rect.height)).AppendLine(";");
        }

        /// <summary>Relative flex-flow layout for a child of an Auto Layout container: sizing follows
        /// the child's Fixed/Hug/Fill policy, and spacing becomes a leading margin on the main axis for
        /// every child after the first.</summary>
        private static void AppendFlowChildLayout(StringBuilder sb, DesignerMetadataAsset metadata,
            DesignerElementMetadata element, DesignerAutoLayoutMetadata parentLayout)
        {
            var self = element.autoLayout ?? new DesignerAutoLayoutMetadata();
            var mainIsRow = parentLayout.direction == DesignerAutoLayoutDirection.Row;

            sb.AppendLine("    position: relative;");

            EmitAxisSize(sb, "width", self.widthSizing, element.rect.width, fillOnMainAxis: mainIsRow);
            EmitAxisSize(sb, "height", self.heightSizing, element.rect.height, fillOnMainAxis: !mainIsRow);

            if (parentLayout.spacing > 0f && !IsFirstAmongSiblings(metadata, element))
            {
                var margin = mainIsRow ? "margin-left" : "margin-top";
                sb.Append("    ").Append(margin).Append(": ").Append(Px(parentLayout.spacing)).AppendLine(";");
            }
        }

        private static void EmitAxisSize(StringBuilder sb, string property, DesignerAutoLayoutSizing sizing, float fixedValue, bool fillOnMainAxis)
        {
            switch (sizing)
            {
                case DesignerAutoLayoutSizing.Fixed:
                    sb.Append("    ").Append(property).Append(": ").Append(Px(fixedValue)).AppendLine(";");
                    break;
                case DesignerAutoLayoutSizing.Fill:
                    sb.Append("    ").Append(property).AppendLine(": auto;");
                    if (fillOnMainAxis) sb.AppendLine("    flex-grow: 1;");
                    break;
                case DesignerAutoLayoutSizing.Hug:
                    sb.Append("    ").Append(property).AppendLine(": auto;");
                    break;
            }
        }

        private static bool IsFirstAmongSiblings(DesignerMetadataAsset metadata, DesignerElementMetadata element)
        {
            var siblings = DesignerHierarchyUtility.GetOrderedChildren(metadata, element.parentId);
            return siblings.Count == 0 || siblings[0] == element;
        }

        // ---- Mapping helpers ----------------------------------------------------

        private static readonly Dictionary<string, string> TagMap = new Dictionary<string, string>
        {
            { "Label", "ui:Label" },
            { "Button", "ui:Button" },
            { "IconButton", "ui:Button" },
            { "Toggle", "ui:Toggle" },
        };

        private static readonly HashSet<string> TextTypes = new HashSet<string> { "Label", "Button", "IconButton" };

        private static string TagFor(string elementType)
            => !string.IsNullOrEmpty(elementType) && TagMap.TryGetValue(elementType, out var tag) ? tag : "ui:VisualElement";

        private static bool HasText(string elementType)
            => !string.IsNullOrEmpty(elementType) && TextTypes.Contains(elementType);

        private static string ClassAttr(DesignerElementMetadata element)
        {
            if (element.classes == null || element.classes.Count == 0) return string.Empty;
            var parts = new List<string>();
            foreach (var c in element.classes)
                if (!string.IsNullOrEmpty(c)) parts.Add(c);
            return string.Join(" ", parts);
        }

        private static string Px(float value)
            => Mathf.RoundToInt(value).ToString(CultureInfo.InvariantCulture) + "px";

        private static string Rgba(Color color)
        {
            int r = Mathf.Clamp(Mathf.RoundToInt(color.r * 255f), 0, 255);
            int g = Mathf.Clamp(Mathf.RoundToInt(color.g * 255f), 0, 255);
            int b = Mathf.Clamp(Mathf.RoundToInt(color.b * 255f), 0, 255);
            var a = color.a.ToString("0.###", CultureInfo.InvariantCulture);
            return $"rgba({r}, {g}, {b}, {a})";
        }

        private static string EscapeAttr(string value)
        {
            if (string.IsNullOrEmpty(value)) return string.Empty;
            return value
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;");
        }
    }
}
