using System.Collections.Generic;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace emiteat.NexUI.Designer.Editor.Contracts
{
    /// <summary>
    /// Generates a C# constants file for a screen's element ids and binding keys so game
    /// code can reference them without magic strings. Never overwrites arbitrary user code:
    /// the target path is user-selectable (default <c>Assets/NexUI/Generated</c>) and files
    /// are clearly named &lt;ScreenId&gt;Ids.cs.
    /// </summary>
    public static class ContractCodeGenerator
    {
        private const string DefaultFolder = "Assets/NexUI/Generated";

        public static string Generate(DesignerMetadataAsset metadata, string interactivePath = null)
        {
            if (metadata == null) return null;

            var screenId = string.IsNullOrEmpty(metadata.screenId) ? "Screen" : metadata.screenId;
            var className = Sanitize(screenId, true) + "Ids";
            var defaultPath = DefaultFolder + "/" + className + ".cs";

            var path = interactivePath ?? EditorUtility.SaveFilePanelInProject(
                "Generate NexUI Constants", className + ".cs", "cs",
                "Choose where to write the generated element-id / binding-key constants.",
                EnsureFolder(DefaultFolder) ? DefaultFolder : "Assets");
            if (string.IsNullOrEmpty(path)) return null;

            var code = BuildSource(metadata, className, screenId);
            System.IO.File.WriteAllText(path, code);
            AssetDatabase.ImportAsset(path);
            var obj = AssetDatabase.LoadAssetAtPath<Object>(path);
            if (obj != null) EditorGUIUtility.PingObject(obj);
            return path;
        }

        private static string BuildSource(DesignerMetadataAsset metadata, string className, string screenId)
        {
            var elementIds = new SortedDictionary<string, string>();
            var commandKeys = new SortedDictionary<string, string>();
            var valueKeys = new SortedDictionary<string, string>();

            foreach (var e in metadata.elements)
            {
                if (e == null || string.IsNullOrEmpty(e.elementId)) continue;
                elementIds[Sanitize(e.elementId, true)] = e.elementId;
                if (e.binding != null)
                {
                    if (!string.IsNullOrEmpty(e.binding.commandKey)) commandKeys[Sanitize(e.binding.commandKey, true)] = e.binding.commandKey;
                    if (!string.IsNullOrEmpty(e.binding.valueKey)) valueKeys[Sanitize(e.binding.valueKey, true)] = e.binding.valueKey;
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by NexUI Designer. Do not edit by hand; regenerate from the UI Contract window.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("namespace NexUI.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>Constants for screen '{screenId}'.</summary>");
            sb.AppendLine($"    public static class {className}");
            sb.AppendLine("    {");
            sb.AppendLine("        public const string ScreenId = " + Quote(screenId) + ";");
            AppendGroup(sb, "Element ids", "Element", elementIds);
            AppendGroup(sb, "Command keys", "Command", commandKeys);
            AppendGroup(sb, "Value keys", "Value", valueKeys);
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void AppendGroup(StringBuilder sb, string header, string prefix, SortedDictionary<string, string> items)
        {
            if (items.Count == 0) return;
            sb.AppendLine();
            sb.AppendLine("        // " + header);
            foreach (var pair in items)
                sb.AppendLine($"        public const string {prefix}_{pair.Key} = {Quote(pair.Value)};");
        }

        private static bool EnsureFolder(string folder)
        {
            if (AssetDatabase.IsValidFolder(folder)) return true;
            if (!AssetDatabase.IsValidFolder("Assets/NexUI"))
                AssetDatabase.CreateFolder("Assets", "NexUI");
            if (!AssetDatabase.IsValidFolder(folder))
                AssetDatabase.CreateFolder("Assets/NexUI", "Generated");
            return AssetDatabase.IsValidFolder(folder);
        }

        private static string Sanitize(string raw, bool pascal)
        {
            if (string.IsNullOrEmpty(raw)) return "_";
            var sb = new StringBuilder();
            bool upNext = pascal;
            foreach (var c in raw)
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(upNext ? char.ToUpperInvariant(c) : c);
                    upNext = false;
                }
                else upNext = true;
            }
            if (sb.Length == 0 || char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }

        private static string Quote(string s) => "\"" + (s ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
